//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ---- MQTTValve ----

func (in *MQTTValve) DeepCopyInto(out *MQTTValve) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MQTTValve) DeepCopy() *MQTTValve {
	if in == nil {
		return nil
	}
	out := new(MQTTValve)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTValve) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTValveList) DeepCopyInto(out *MQTTValveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTValve, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MQTTValveList) DeepCopy() *MQTTValveList {
	if in == nil {
		return nil
	}
	out := new(MQTTValveList)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTValveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTValveSpec) DeepCopyInto(out *MQTTValveSpec) {
	*out = *in
}

func (in *MQTTValveSpec) DeepCopy() *MQTTValveSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTValveSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTValveStatus) DeepCopyInto(out *MQTTValveStatus) {
	*out = *in
	if in.LastOpenTime != nil {
		in, out := &in.LastOpenTime, &out.LastOpenTime
		*out = (*in).DeepCopy()
	}
	if in.LastCloseTime != nil {
		in, out := &in.LastCloseTime, &out.LastCloseTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MQTTValveStatus) DeepCopy() *MQTTValveStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTValveStatus)
	in.DeepCopyInto(out)
	return out
}

// ---- MQTTDevice ----

func (in *MQTTDevice) DeepCopyInto(out *MQTTDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MQTTDevice) DeepCopy() *MQTTDevice {
	if in == nil {
		return nil
	}
	out := new(MQTTDevice)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTDeviceList) DeepCopyInto(out *MQTTDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MQTTDeviceList) DeepCopy() *MQTTDeviceList {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceList)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTDeviceSpec) DeepCopyInto(out *MQTTDeviceSpec) {
	*out = *in
	out.BridgeRef = in.BridgeRef
	if in.TypeRef != nil {
		in, out := &in.TypeRef, &out.TypeRef
		*out = new(TypeRef)
		**out = **in
	}
}

func (in *MQTTDeviceSpec) DeepCopy() *MQTTDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTDeviceStatus) DeepCopyInto(out *MQTTDeviceStatus) {
	*out = *in
	if in.LastSeenTime != nil {
		in, out := &in.LastSeenTime, &out.LastSeenTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MQTTDeviceStatus) DeepCopy() *MQTTDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// ---- MQTTBridge ----

func (in *MQTTBridge) DeepCopyInto(out *MQTTBridge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MQTTBridge) DeepCopy() *MQTTBridge {
	if in == nil {
		return nil
	}
	out := new(MQTTBridge)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTBridge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTBridgeList) DeepCopyInto(out *MQTTBridgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTBridge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MQTTBridgeList) DeepCopy() *MQTTBridgeList {
	if in == nil {
		return nil
	}
	out := new(MQTTBridgeList)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTBridgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTBridgeSpec) DeepCopyInto(out *MQTTBridgeSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(BridgeCredentialsRef)
		**out = **in
	}
}

func (in *MQTTBridgeSpec) DeepCopy() *MQTTBridgeSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTBridgeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTBridgeStatus) DeepCopyInto(out *MQTTBridgeStatus) {
	*out = *in
	if in.LastConnectedTime != nil {
		in, out := &in.LastConnectedTime, &out.LastConnectedTime
		*out = (*in).DeepCopy()
	}
	if in.LastDisconnectedTime != nil {
		in, out := &in.LastDisconnectedTime, &out.LastDisconnectedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MQTTBridgeStatus) DeepCopy() *MQTTBridgeStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTBridgeStatus)
	in.DeepCopyInto(out)
	return out
}

// ---- Shared types ----

func (in *NamespacedRef) DeepCopyInto(out *NamespacedRef) {
	*out = *in
}

func (in *TypeRef) DeepCopyInto(out *TypeRef) {
	*out = *in
}

func (in *BridgeCredentialsRef) DeepCopyInto(out *BridgeCredentialsRef) {
	*out = *in
}
