apiVersion: v1
kind: Service
metadata:
  name: {{ include "valve-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valve-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "valve-controller.selectorLabels" . | nindent 4 }}
